version: '3'
services:
  postgres:
    image: postgres:15.4-bookworm
    container_name: odin-twitter-postgres-15.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      "postgres -c max_connections=500"
    environment:
      - POSTGRES_DB=odin_twitter_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6400:6379"

  web:
    build: .
    tty: true
    # command: "bin/dev"
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - POSTGRES_PASSWORD=Password
      - POSTGRES_USER=postgres
      - RAILS_ENV=production
      - POSTGRES_DB=odin_twitter_production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"

volumes:
  postgres-data: {}
  app-storage: {}
  redis: {}
