version: '3.8'

services:
    postgres:
        image: postgres:16.0-bookworm
        container_name: odin-quacker-postgres-16.0
        volumes:
            - postgres-data:/var/lib/postgresql/data
        command: "postgres -c max_connections=500"
        env_file:
            - .env
        ports:
            - "5432:5432"

    redis:
        image: redis:7.2.3-alpine
        command: redis-server
        volumes:
            - redis:/data
        env_file:
            - .env
        ports:
            - "6379:6379"

    web:
        build: .
        tty: true
        env_file:
            - .env
        environment:
            - SSL='false'
        volumes:
            - .:/app  # Mount entire app
            - app-storage:/rails/storage
        depends_on:
            - postgres
            - redis
        links:
            - postgres
            - redis
        ports:
            - "3000:3000"

    sidekiq:
        build: .
        env_file:
            - .env
        command: bundle exec sidekiq -C config/sidekiq.yml
        entrypoint: []
        depends_on:
            postgres:
                condition: service_started
                required: false
            redis:
                condition: service_started
                required: false
        volumes:
            - .:/app  # Ensure Sidekiq has access to app code
            - app-storage:/rails/public
        tty: true

volumes:
    postgres-data: {}
    app-storage: {}
    redis: {}