version: "3"
services:
    postgres:
        image: postgres:16.0-bookworm
        container_name: odin-twitter-postgres-16.0
        volumes:
            - postgres-data:/var/lib/postgresql/data
        command: "postgres -c max_connections=500"
        env_file:
            - .env
        ports:
            - "5432:5432"

    redis:
        image: redis:7.2.3-alpine
        command: redis-server
        volumes:
            - redis:/data
        ports:
            - "6379:6379"

    web:
        build: .
        tty: true
        env_file:
            - ".env"
        volumes:
            - app-storage:/rails/storage
        depends_on:
            - postgres
            - redis
        links:
            - postgres
            - redis
        ports:
            - "3000:3000"

    sidekiq:
        build:
            context: .
        env_file:
            - .env
        command: bundle exec sidekiq -e production -q critical -q high -q default -q low -C config/sidekiq.yml
        entrypoint: []
        depends_on:
            postgres:
                condition: "service_started"
                required: false
            redis:
                condition: "service_started"
                required: false
        volumes:
            - /rails/public
        tty: true

volumes:
    postgres-data: {}
    app-storage: {}
    redis: {}
