default: &default
  adapter: "redis"
  # url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  url:  "redis://redis:6379/1"
  # url: <%= ENV["REDIS_PRIVATE_URL"] %>
  # port: <%= ENV["REDIS_PORT"] %>
  # for some reason have to use this localhost link when using docker-compose-utils + bin/dev, as it was having issues with turbo streams/jobs clashing?


development:
  <<: *default
  channel_prefix: odin_twitter_development

test:
  <<: *default
  adapter: test

production:
  <<: *default
  channel_prefix: odin_twitter_production
