default: &default
  adapter: postgresql
  encoding: unicode

  # database: <%= ENV.fetch("POSTGRES_DB") { "hello" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "hello" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "hello" } %>_development
  # username: <%= ENV.fetch("POSTGRES_USER") { "hello" } %>
  # host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  # password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>


test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "hello" } %>_test
  username: <%= ENV.fetch("POSTGRES_USER") { "hello" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>

production:
  <<: *default
  database: odin_twitter_production
  username: <%= ENV.fetch("POSTGRES_USER") { "hello" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
