default: &default
  adapter: postgresql
  encoding: unicode

  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV["RAILS_MAX_THREADS"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>_development

test:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>_production
