---

:verbose: false
:concurrency: 10
:timeout: 25

:queues:
  - critical
  - default
  - mailers
  - low

:schedule:
  muted_words_cleanup:
    class: MutedWordsCleanupJob
    queue: default

production:
  :concurrency: 25
staging:
  :concurrency: 15
